server:
  log_level: info

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: varlogs
          static_configs:
            - targets: [localhost]
              labels:
                job: varlogs
                __path__: /var/log/*log
      clients:
        - url: http://localhost:3100/loki/api/v1/push

integrations:
  node_exporter:
    enabled: true